In [ ]:
import numpy as np
from sympy import *

# 행렬 A의 첨가행렬을 기약 행 사다리꼴로 변환
# np.hstack(A, b) : 행렬 A에 벡터 b를 붙여 첨가행렬 만들기
# Matrix(): 행렬을 의미
A = np.array([[1,3,2],[2,2,0],[-3,1,1]])
b = np.array([[2,0,-2]])

augmented_A = Matrix(np.hstack((A, b.T)))
print("행렬 A의 첨가행렬 = \n", np.array(augmented_A))
print("\n")
print("행렬 A의 첨가행렬의 기약 행 사다리꼴 = \n", np.array(augmented_A.rref()[0]))

행렬 A의 첨가행렬 = 
 [[1 3 2 2]
 [2 2 0 0]
 [-3 1 1 -2]]


행렬 A의 첨가행렬의 기약 행 사다리꼴 = 
 [[1 0 0 1]
 [0 1 0 -1]
 [0 0 1 2]]


In [ ]:
import numpy as np

# 행렬 A의 역행렬 계산
# np.linalg.matrix_power(A,n): 행렬 A의 n제곱
# np.linalg.matrix_power(A,-1): 행렬 A의 역행렬
A = np.array([[2,3],[5,7]])
A_inv = np.linalg.matrix_power(A, -1)
print("Inverse matrix of A = \n", A_inv)

Inverse matrix of A = 
 [[-7.  3.]
 [ 5. -2.]]


In [ ]:
import numpy as np

# 행렬 A의 역행렬 계산
# np.linalg.inv(A): 행렬 A의 역행렬
A = np.array([[1,3,2],[2,2,0],[-3,1,1]])
A_inv = np.linalg.inv(A)
print("Inverse matrix of A = \n", A_inv)

Inverse matrix of A = 
 [[ 0.16666667 -0.08333333 -0.33333333]
 [-0.16666667  0.58333333  0.33333333]
 [ 0.66666667 -0.83333333 -0.33333333]]


In [ ]:
import numpy as np

# 행렬 A의 전치행렬 구하기
# A.T: 행렬 A의 전치행렬
A = np.array([[-1,3],[3,7]])
A_T = A.T
print("Transposed matrix of A = \n", A_T)
print("\n")

# 행렬 B의 전치행렬 구하기
B = np.array([[1,3,5],[7,2,9],[10,11,3]])
B_T = B.T
print("Transposed matrix of B = \n", B_T)
print("\n")

Transposed matrix of A = 
 [[-1  3]
 [ 3  7]]


Transposed matrix of B = 
 [[ 1  7 10]
 [ 3  2 11]
 [ 5  9  3]]




In [ ]:
import numpy as np

A = np.array([[1,2,0],[3,2,1],[2,-1,1]])
B = np.array([[1,-2,3],[1,4,2],[-1,0,7]])

# 행렬 AB의 계산과 행렬 AB의 대각합 계산
# np.trace(A): 행렬 A의 대각합
AB = np.matmul(A,B)
tr_AB = np.trace(AB)
print("AB =\n", AB)
print("\n")
print("Trace of AB = ", tr_AB)
print("\n")

# 행렬 BA의 계산과 행렬 BA의 대각합 계산
BA = np.matmul(B,A)
tr_BA = np.trace(BA)
print("BA =\n", BA)
print("\n")
print("Trace of BA = ", tr_BA)
print("\n")

print("행렬 AB와 행렬 BA는 같은가?", np.array_equal(AB, BA))
print("tr(AB)와 tr(BA)는 같은가?", tr_AB == tr_BA)


AB =
 [[ 3  6  7]
 [ 4  2 20]
 [ 0 -8 11]]


Trace of AB =  16


BA =
 [[ 1 -5  1]
 [17  8  6]
 [13 -9  7]]


Trace of BA =  16


행렬 AB와 행렬 BA는 같은가? False
tr(AB)와 tr(BA)는 같은가? True


In [ ]:
import numpy as np

# 문제 (a)
A = np.array([[1,0,0,1],[0,1,2,0],[0,2,1,0],[1,0,0,5]])
A_inv = np.linalg.matrix_power(A,-1)
print("(a) Inverse matrix of A = \n", A_inv)
print("\n")

# 문제 (b)
B = np.array([[2,3],[3,4]])
B_inv = np.linalg.matrix_power(B,-1)
print("(b) Inverse matrix of B = \n", B_inv)
print("\n")

# 문제 (c)
C = np.array([[9,-4,6],[5,-3,6],[-3,1,-2]])
C_inv = np.linalg.matrix_power(C,-1)
print("(c) Inverse matrix of C = \n", C_inv)
print("\n")

(a) Inverse matrix of A = 
 [[ 1.25        0.          0.         -0.25      ]
 [ 0.         -0.33333333  0.66666667  0.        ]
 [ 0.          0.66666667 -0.33333333  0.        ]
 [-0.25        0.          0.          0.25      ]]


(b) Inverse matrix of B = 
 [[-4.  3.]
 [ 3. -2.]]


(c) Inverse matrix of C = 
 [[ 0.    -0.25  -0.75 ]
 [-1.    -0.    -3.   ]
 [-0.5    0.375 -0.875]]


