In [ ]:
import numpy as np

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[-2,4],[1,3]])
C = np.array([[2,-5],[3,-2]])
D = np.array([[5,-1,3],[-4,3,-6],[-3,1,2]])

In [13]:
# (a) A[2,2] + B[1,1]
print("문제(a) = ", A[1,1]+B[0,0])
print("\n")

# (b) (A^T)^T
# A.T: 행렬 A의 전치행렬
print("문제 (b) = \n", (A.T).T)
print("\n")

# (c) B^T
print("문제 (c) = \n", B.T)
print("\n")

# (d) A^T + B^T
print("문제 (d) = \n", (A.T) + (B.T))
print("\n")

# (e) (A + B)^T
print("문제 (e) = \n", (A+B).T)
print("\n")

# (f) 3I_2 - C
# np.eye(n): n * n 크기의 단위행렬
print("문제 (f) = \n", (3*np.eye(2))-C)
print("\n")

# (g) D - 5I_3
print("문제 (g) = \n", D - (5*np.eye(3)))
print("\n")

# (h) (3I_3)D
print("문제 (h) = \n", np.dot(3*np.eye(3),D))
print("\n")

문제(a) =  2


문제 (b) = 
 [[1 2]
 [3 4]]


문제 (c) = 
 [[-2  1]
 [ 4  3]]


문제 (d) = 
 [[-1  4]
 [ 6  7]]


문제 (e) = 
 [[-1  4]
 [ 6  7]]


문제 (f) = 
 [[ 1.  5.]
 [-3.  5.]]


문제 (g) = 
 [[ 0. -1.  3.]
 [-4. -2. -6.]
 [-3.  1. -3.]]


문제 (h) = 
 [[ 15.  -3.   9.]
 [-12.   9. -18.]
 [ -9.   3.   6.]]


