In [2]:
import numpy as np

# 노름을 구하는 함수
def cal_norm(vec1):
  norm_vec = np.sqrt(np.sum(vec1 * vec1))
  return norm_vec

# 내적을 구하는 함수
def cal_innerproduct(vec1, vec2):
  innerprod_vecs = np.sum(vec1*vec2)
  return innerprod_vecs

# 해밍 거리를 구하는 함수
def cal_hamming_dist(vec1, vec2):
  Num_vec = len(vec1)
  hamming_dist = 0
  for i in range(Num_vec):
    if vec1[i] != vec2[i]:
      hamming_dist += 1
  return hamming_dist

# 맨하튼 거리를 구하는 함수
def cal_Manhattan_dist(vec1, vec2):
  Manhattan_dist = np.sum(np.abs(vec1-vec2))
  return Manhattan_dist

# 벡터 x, y, z, v, w
x = np.array([1,0,1,0])
y = np.array([0,2,2,0])
z = np.array([1,0,1,2])
v = np.array([1,1,1,1])
w = np.array([2,2,0,1])

# 문제 (a)
print("문제 (a)")
print("Norm of x = ", cal_norm(x))
print("Norm of y = ", cal_norm(y))
print("Norm of z = ", cal_norm(z))
print("\n")

# 문제 (b)
print("문제 (b)")
print("Inner product of x and y = ", cal_innerproduct(x,y))
print("\n")

# 문제 (c)
print("문제 (c)")
print("Inner product of z and x+y = ", cal_innerproduct(z, x+y))
print("\n")

# 문제 (d)
print("문제 (d)")
print("Hamming distance of x and v = ", cal_hamming_dist(x,v))
print("\n")

# 문제 (e)
print("문제 (e)")
print("Manhattan distance of v and w = ", cal_Manhattan_dist(v,w))

문제 (a)
Norm of x =  1.4142135623730951
Norm of y =  2.8284271247461903
Norm of z =  2.449489742783178


문제 (b)
Inner product of x and y =  2


문제 (c)
Inner product of z and x+y =  4


문제 (d)
Hamming distance of x and v =  2


문제 (e)
Manhattan distance of v and w =  3


In [5]:
import numpy as np

# 두 벡터가 이루는 각을 구하는 함수
# np.linalg.norm(vec) : vec의 노름
# np.arctan() : tan()의 역함수 값

def angle_to_vectors(vec_1, vec_2):
    vec_1_norm = np.linalg.norm(vec_1)
    vec_2_norm = np.linalg.norm(vec_2)
    vec_1_2_dot = np.dot(vec_1.T, vec_2)
    angle = np.arctan(vec_1_2_dot/(vec_1_norm*vec_2_norm))*360/np.pi
    return angle

# 정사영을 구하는 함수
def Proj_onto(vec_1, vec_2):
    vec_2_1_dot = np.dot(vec_2.T, vec_1)
    vec_2_dot = np.dot(vec_2.T, vec_2)
    proj_vec = (vec_2_1_dot/vec_2_dot)*vec_2
    return proj_vec

# 문제 (a)
x = np.array([[1], [0]])
y = np.array([[4], [4]])
angle = angle_to_vectors(x, y)
projxy = Proj_onto(y, x)
print("문제 (a)")
print("x와 y가 이루는 각 = ", angle)
print("x의 y 위로의 정사영 = \n", projxy)
print("\n")

# 문제 (b)
x = np.array([[1], [2], [5]])
y = np.array([[1], [-1], [2]])
angle = angle_to_vectors(x, y)
projxy = Proj_onto(y, x)
print("문제 (b)")
print("x와 y가 이루는 각 = ", angle)
print("x의 y 위로의 정사영 = \n", projxy)
print("\n")

# 문제 (c)
x = np.array([[0], [-1], [2], [2]])
y = np.array([[1], [1], [3], [2]])
angle = angle_to_vectors(x, y)
projxy = Proj_onto(y, x)
print("문제 (c)")
print("x와 y가 이루는 각 = ", angle)
print("x의 y 위로의 정사영 = \n", projxy)

문제 (a)
x와 y가 이루는 각 =  [[70.52877937]]
x의 y 위로의 정사영 = 
 [[4.]
 [0.]]


문제 (b)
x와 y가 이루는 각 =  [[67.70902963]]
x의 y 위로의 정사영 = 
 [[0.3]
 [0.6]
 [1.5]]


문제 (c)
x와 y가 이루는 각 =  [[75.52248781]]
x의 y 위로의 정사영 = 
 [[ 0.]
 [-1.]
 [ 2.]
 [ 2.]]
